apiVersion: v1
entries:
  airports-producer:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-12T11:39:28.5699337+03:00"
    description: A Helm chart for Kubernetes
    digest: 8410d15f9cf8cbb9497f9b6ed33192b972d98306b5fbefc6c51855713e56dddf
    name: airports-producer
    type: application
    urls:
    - airports-producer-0.1.0.tgz
    version: 0.1.0
generated: "2023-07-12T11:39:28.5699337+03:00"
